/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CityDiscount: typeof import('./src/components/DiscountSection/CityDiscount.vue')['default']
    Coupon: (typeof import("./src/components/DiscountSectionComponent/Coupon.vue"))["default"]
    DiscountCoupon: typeof import('./src/components/DiscountSection/DiscountCoupon.vue')['default']
    DiscountSection: typeof import('./src/components/DiscountSection/DiscountSection.vue')['default']
    DiscountSectionHeader: typeof import('./src/components/DiscountSection/DiscountSectionHeader.vue')['default']
    ExclusiveOffers: typeof import('./src/components/DiscountSection/ExclusiveOffers.vue')['default']
    GiftPack: typeof import('./src/components/DiscountSection/GiftPack.vue')['default']
    Header: (typeof import("./src/components/Header/Header.vue"))["default"]
    NavBar: typeof import('./src/components/DiscountSection/NavBar.vue')['default']
    NavBat: typeof import('./src/components/DiscountSection/NavBat.vue')['default']
    NextTarget: (typeof import("./src/components/WaitTrips/NextTarget.vue"))["default"]
    OrderList: typeof import('./src/components/TravelAgent/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectOffers: typeof import('./src/components/DiscountSection/SelectOffers.vue')['default']
    SOHead: (typeof import("./src/components/DiscountSection/SOHead.vue"))["default"]
    Tab: typeof import('./src/components/DiscountSection/Tab.vue')['default']
    TopFix: typeof import('./src/components/DiscountSection/TopFix.vue')['default']
    TourItem: typeof import('./src/components/DiscountSection/TourItem.vue')['default']
    TourMsg: typeof import('./src/components/DiscountSection/TourMsg.vue')['default']
    TravelMarketing: typeof import('./src/components/TravelAgent/TravelMarketing.vue')['default']
    TripHeader: typeof import('./src/components/TripHeader/TripHeader.vue')['default']
    TripOrder: typeof import('./src/components/TripOrder/TripOrder.vue')['default']
    TripsOrder: typeof import('./src/components/TripsOrder/TripsOrder.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanDivider: typeof import('vant/es')['Divider']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VueText: (typeof import("./src/components/VueText.vue"))["default"]
    WaitDetail: typeof import('./src/components/TravelAgent/WaitDetail.vue')['default']
    WaitTripOrder: typeof import('./src/components/TravelAgent/WaitTripOrder.vue')['default']
    WaitTrips: typeof import('./src/components/WaitTrips/WaitTrips.vue')['default']
  }
}
