/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CityDiscount: typeof import('./src/components/SpecialOfferComponent/CityDiscount.vue')['default']
    Coupon: typeof import('./src/components/SpecialOfferComponent/Coupon.vue')['default']
    DiscountCoupon: typeof import('./src/components/SpecialOfferComponent/DiscountCoupon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectOffers: typeof import('./src/components/SpecialOfferComponent/SelectOffers.vue')['default']
    SOHead: typeof import('./src/components/SpecialOfferComponent/SOHead.vue')['default']
    TopFix: typeof import('./src/components/SpecialOfferComponent/TopFix.vue')['default']
    TourMsg: typeof import('./src/components/SpecialOfferComponent/TourMsg.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VueText: typeof import('./src/components/VueText.vue')['default']
  }
}
